// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package schema

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type PaymentPaymentMethod string

const (
	PaymentPaymentMethodMobileMoney  PaymentPaymentMethod = "mobile_money"
	PaymentPaymentMethodCard         PaymentPaymentMethod = "card"
	PaymentPaymentMethodOnline       PaymentPaymentMethod = "online"
	PaymentPaymentMethodBankTransfer PaymentPaymentMethod = "bank_transfer"
	PaymentPaymentMethodCash         PaymentPaymentMethod = "cash"
	PaymentPaymentMethodOther        PaymentPaymentMethod = "other"
)

func (e *PaymentPaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentPaymentMethod(s)
	case string:
		*e = PaymentPaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentPaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentPaymentMethod struct {
	PaymentPaymentMethod PaymentPaymentMethod
	Valid                bool // Valid is true if PaymentPaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentPaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentPaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentPaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusPending  PaymentStatus = "pending"
	PaymentStatusPaid     PaymentStatus = "paid"
	PaymentStatusFailed   PaymentStatus = "failed"
	PaymentStatusRefunded PaymentStatus = "refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type ReservationState string

const (
	ReservationStatePending    ReservationState = "pending"
	ReservationStateConfirmed  ReservationState = "confirmed"
	ReservationStateInProgress ReservationState = "in_progress"
	ReservationStateCompleted  ReservationState = "completed"
	ReservationStateCancelled  ReservationState = "cancelled"
)

func (e *ReservationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationState(s)
	case string:
		*e = ReservationState(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationState: %T", src)
	}
	return nil
}

type NullReservationState struct {
	ReservationState ReservationState
	Valid            bool // Valid is true if ReservationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationState) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationState), nil
}

type AuditLog struct {
	ID        int32
	UserID    sql.NullInt32
	Action    string
	TableName string
	RecordID  int32
	OldValue  sql.NullString
	NewValue  sql.NullString
	CreatedAt time.Time
}

type Employee struct {
	ID        int32
	GarageID  int32
	Name      string
	Phone     string
	Email     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Garage struct {
	ID        int32
	Name      string
	Address   string
	Phone     string
	Email     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type MaintenancePackage struct {
	ID            int32
	ServiceTypeID int32
	Name          string
	Description   string
	Price         int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type Payment struct {
	ID               int32
	ReservationID    int32
	Amount           int32
	Status           PaymentStatus
	PaymentMethod    PaymentPaymentMethod
	PaymentProvider  sql.NullString
	PaymentReference sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        sql.NullTime
}

type RefreshToken struct {
	ID        int32
	UserID    int32
	TokenHash string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Reservation struct {
	ID                   int32
	MaintenancePackageID int32
	UserID               int32
	VehicleID            int32
	State                ReservationState
	ScheduledAt          time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DeletedAt            sql.NullTime
}

type ServiceType struct {
	ID          int32
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Session struct {
	ID        int32
	UserID    int32
	TokenHash string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type Vehicle struct {
	ID           int32
	UserID       int32
	Brand        string
	Model        string
	LicensePlate string
	Year         sql.NullInt32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
