// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package schema

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :execresult
INSERT INTO session (
  user_id, token_hash, updated_at
) VALUES (
  ?, ?, ?
)
`

type CreateSessionParams struct {
	UserID    int32
	TokenHash string
	UpdatedAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSession, arg.UserID, arg.TokenHash, arg.UpdatedAt)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO user (
  name, email, password_hash, updated_at
) VALUES (
  ?, ?, ?, NOW()
)
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, created_at, updated_at, deleted_at FROM session
WHERE token_hash = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, password_hash, created_at, updated_at, deleted_at FROM user
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByMail = `-- name: GetUserByMail :one
SELECT id, name, email, password_hash, created_at, updated_at, deleted_at FROM user
WHERE email = ?
LIMIT 1
`

func (q *Queries) GetUserByMail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByMail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM user
WHERE id = ?
`

func (q *Queries) HardDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, hardDeleteUser, id)
	return err
}

const showSoftDeletedUsers = `-- name: ShowSoftDeletedUsers :many
SELECT id, name, email, password_hash, created_at, updated_at, deleted_at FROM user
WHERE deleted_at IS NOT NULL
`

func (q *Queries) ShowSoftDeletedUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, showSoftDeletedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSessionByTokenHash = `-- name: SoftDeleteSessionByTokenHash :exec
UPDATE session
SET deleted_at = NOW()
WHERE token_hash = ?
`

func (q *Queries) SoftDeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, softDeleteSessionByTokenHash, tokenHash)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE user
SET deleted_at = NOW()
WHERE id = ?
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}
